source "https://rubygems.org"

# Core Jekyll
gem "jekyll", "~> 4.3"

# GitHub Pages compatible plugins
group :jekyll_plugins do
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
  gem "jekyll-feed"
end

# Windows and JRuby does not include zoneinfo files
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1", :platforms => [:mingw, :x64_mingw, :mswin]

# Lock http_parser to older version for JRuby
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]

# Needed for Ruby 3.0+
gem "webrick", "~> 1.8"
